import type { Metadata } from "next";
import { Patrick_Hand } from "next/font/google";

import "./globals.css";

const patrickHand = Patrick_Hand({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  ${patrickHand.className}   antialiased dark`}>
        {children}
      </body>
    </html>
  );
}
